### PR TITLE
Flickr exporter

### LINKED ISSUE #1: [RFP] Flickr -> Textile Import/Export Tool 📷
---
name: Request For Flickr -> Textile Import/Export Tool 📷
about: Similarly to the existing Facebook/Instagram import tool, it would be great to have a quick way to import Flickr photos into Textile Photos!
---

Request

**How would this project demonstrate the Textile technology? What problem does it help solve? Please describe.**

Flickr was purchased in April 2018 by professional photo hosting service SmugMug, and shortly thereafter, announced that free accounts would now be limited to 1000 pictures on the photo sharing site, instead of the free 1TB of storage that was previously offered. Free users with more than 1000 photos or videos had until January 8th, 2019, to upgrade to Pro or download their surplus content. And on February 5th, 2019 (this week!), free accounts that are still over the limit will have their content actively deleted until they're back under 1000 [original source](https://www.theverge.com/2018/11/1/18051950/flickr-1000-photo-limit-free-accounts-changes-pro-subscription-smugmug).

For Textile Photos users, this change in terms presents an opportunity to move photos and content to Textile Photos, where they'll have greater control over the fate of their photos. In this proposal, we suggest building a desktop/command-line tool to pull Flickr photo data from Flickr™️ (or a local data dump), and automatically create Textile Photos groups for subsequent sharing etc.

This project would/could utilize existing Textile examples ([see here](https://github.com/textileio/textile-explore/tree/master/facebook)), and would build upon Textile's command-line tools for creating and modifying groups or threads. It would also provide an example of using Textile tooling to share data via a Cafe or Server Peer.

**Describe the solution you'd like**

Ideally, this project would 'fork' or otherwise benefit from [previous work](https://github.com/textileio/textile-explore/tree/master/facebook) on a Facebook™️ import/export tool built by the Textile team. However, any simple tool or interface would be potentially acceptable. For this particular RFP, a simple desktop/command-line tool would be ideal.

**Describe alternatives you've considered**

Since this tooling doesn't yet exist, there aren't many alternatives. One alternative would be a tool that imports a folder or folders of photos into Textile groups... however, it would be much more useful to automatically extract photo data (and metadata) from Flickr™️ directly to make this useful. In fact, a solution that uses a user's Flickr™️ API credentials to extract their own photos/data is preferred.

**Documentation & Adoption Strategy**

For a potential example, please see [this existing Textile Explore project](https://github.com/textileio/textile-explore/tree/master/facebook) for Facebook™️ data. The preferred technology is Python, and the preferred interface is a desktop/command-line tool. However, other solutions would be considered. Something like this would be useful:

```
python3 flickr2textile.py -k <api-key> -s <api-secret> -u username
```

Where the api-key and secret would be those required by the [Flickr™️ API](https://www.flickr.com/services/api/). The username would be used to communicate with the `Person` API endpoint. Alternative access tools/methods would also be considered.

A blog post or documentation for the usage would also be required, and, after some editorial input, could be published on the Textile blog. Ideally, the documentation would be sufficient that a novice developer, or someone only moderately familiar with Textile, Flickr, and scripting, could follow along.

### PR DESCRIPTION
**Pull request by robbynshaw**
Closes #1 

Created a basic textile client in the flickr-exporter/textile directory. This directory has it's own package.json with a little bit of basic configuration in case it needs to get pulled out and put somewhere else.

All javascript done with prettier/airbnb standards.

Got the basic photo data pulled from flickr finally. Next is to get it into the textile node.

### CODE REVIEW

**Comment by robbynshaw** [comment]
This branch is now ready for review.

One big caveat-- the textile library needs to be added to `./dev/js-textile-http-client` for it to work currently, and the latest pull request to that library needs to be included.

Once the client library is up on npm, this won't be an issue anymore, but I wasn't quite sure how to handle it now.

I was hoping to get a pretty GIF in the README for you guys, but I can't seem to figure out how to do that in i3 . . . so I will try that some other time.

**Comment by robbynshaw** [comment]
Updated for the new client library. Also switch to yarn in the lock file and readme.

And here is the GIF... (if anyone abuses my secrets, I'll just de-authorize the tokens).

fickr-export

**Comment by carsonfarmer** [comment]
This looks fantastic @robbynshaw. Which version of the `textile-go` peer did you develop this against? Just so we know when testing. Things are moving quick in that repo, so the APIs etc are changing underneath us. Not a problem for this project, we'll just use whichever release you developed with 👍

**Comment by robbynshaw** [comment]
Thanks @carsonfarmer. I developed this against 1.0.0-rc23. I also added the links and that version information to the README as requested.

**Pull request merged**
